### ISSUE TITLE
Deletation does not work on iOS 13/Xcode 11

### ISSUE THREAD

**Issue by nikolaveljic64** [marinofelipe/CurrencyText#46]
We can’t delete characters on TextField on iOS 13 on physical device.On simulator it is ok. 

I tested on two device : XS Max , 8.

**Comment by marinofelipe** [comment]
Hi @nikolaveljic64, thanks for opening the issue.
I'm going to check it out. Feel free also to fork, and contribute if you want to.

**Comment by marinofelipe** [comment]
Oh, yes, this is a bug with currencies that have the currency symbol at the end, therefore can occur in any os version. 
I will fix this.

**Comment by nikolaveljic64** [comment]
Hi @marinofelipe .
Yes , it is problem with currency symbol at the end. I see , on simulator i have $ symbol on beginning , and that working , on my device i have € on end , and that don't.

But you must to know , on iOS 12 when symbol is at the end , that was working. After update on iOS 13 , bug appear.

Thanks.

**Comment by marinofelipe** [comment]
Hello @nikolaveljic64 this should be fixed by #48 . Please try the latest `2.0.5` version.

**Comment by nikolaveljic64** [comment]
Hi @marinofelipe .
It's same.

**Comment by marinofelipe** [comment]
@nikolaveljic64, did you update to 2.0.5? It works here for both simulators and devices when using the latest version.

**Comment by nikolaveljic64** [comment]
@marinofelipe  Yes.
See: 
![ezgif com-optimize](https://user-images.githubusercontent.com/18101315/65873988-e2b1c480-e384-11e9-8392-1a346870f8b5.gif)
<img width="204" alt="Screen Shot 2019-09-30 at 1 18 06 PM" src="https://user-images.githubusercontent.com/18101315/65874003-f5c49480-e384-11e9-95ab-698c05b81697.png">

**Comment by marinofelipe** [comment]
Hi Nikola,

Thank you for sending me this and for contributing.
Also feel free to request any nice functionality, etc.

[image: textfield.gif]

This is strange, because testing on my device the behaviour is correct when
adding/inputing numbers. (see above).
About when the user reselects the field, you're right, I didn't update it,
but is indeed a really good point.

I will work on setting the correct selected text range for the latest case.
And please, if you keep having the issue with adding more characters,
differently from what you've seen above, let me know, so we can check if it
happens for a specific configuration of formatter, device model, or
something else.

I will add a summary of what we talk here to the issue so we can have it
documented there.

Thanks!

**Comment by marinofelipe** [comment]
Hi @nikolaveljic64 ,

About having the selected text range, also before the currency symbol, when the last is at the end, I didn't update it, but is indeed a really good point. I will make a PR to do this improvement.

Just to confirm, did 2.0.5 fixed the selected text range position when one add more numbers? It should now be correctly before the currency symbol, when needed.

**Comment by nikolaveljic64** [comment]
HI @marinofelipe .
Yes.You are right.

**Comment by marinofelipe** [comment]
Hello @nikolaveljic64 . **2.0.6** is now released! Can you please check? Thanks!

**Comment by nikolaveljic64** [comment]
@marinofelipe Hi :) 

I'm already use it. For now everything is ok. If i find something wrong, a will tell tell you. 👍

**Comment by marinofelipe** [comment]
Nice, @nikolaveljic64 . 
Thanks again for your contribution! And if you also have any suggestions, ideas or anything, feel free to open other issues or contact me :).
